[information]
name = "flexoki"
background = "dark"
author = 'Created by stephango.com, implemented by @stevedylandev'

[palette]
fg = '#CECDC3'
bg = '#100F0F'

alt_fg = '#878580'
alt_bg = '#1C1B1A'
dark = '#100F0F'
accent = '#575653'
popup_back = '#282726'
search_orange = '#BC5215'
line = '#282726'

search_blue = '#24837B'
white = '#CECDC3'
gray = '#878580'
dark_gray = '#575653'
context = '#878580'
light_gray = '#878580'
tree_gray = '#282726'
blue = '#205EA6'
vivid_blue = '#4385BE'
dark_blue = '#205EA6'
folder_blue = '#205EA6'
light_blue = '#4385BE'
green = '#66800B'
cyan = '#24837B'
light_green = '#BC5215'
red = '#AF3029'
orange = '#BC5215'
light_red = '#AF3029'
yellow = '#AD8301'
purple = '#5E409D'
magenta = '#A02F6F'

cursor_fg = '#575653'
cursor_bg = '#878580'

sign_add = '#66800B'
sign_change = '#205EA6'
sign_delete = '#AF3029'
tree_sign_add = '#66800B'
tree_sign_change = '#AD8301'

error_red = '#AF3029'
warning_orange = '#BC5215'
info_yellow = '#AD8301'
hint_blue = '#205EA6'
success_green = '#66800B'

purple_test = '#5E409D'
cyan_test = '#24837B'

ui_blue = '#205EA6'
ui2_blue = '#205EA6'
ui3_blue = '#205EA6'
ui4_blue = '#205EA6'
ui_orange = '#BC5215'
ui_purple = '#5E409D'

[highlights]
Normal = 'fg bg'
SignColumn = '- bg'
MsgArea = 'fg bg'
ModeMsg = 'fg dark'
MsgSeparator = 'fg bg'
SpellBad = 'light_red - u'
SpellCap = 'yellow - u'
SpellLocal = 'green - u'
SpellRare = 'purple - u'
NormalNC = 'fg bg'
Pmenu = 'light_gray tree_gray - - 50'
PmenuSel = '- ui2_blue'
WildMenu = 'fg ui2_blue'
CursorLineNr = 'light_gray - b'
Comment = 'gray - i'
Folded = 'accent alt_bg'
FoldColumn = 'accent alt_bg'
LineNr = 'gray -'
FloatBorder = 'gray alt_bg'
Whitespace = 'bg -'
VertSplit = 'gray bg'
CursorLine = '- dark'
CursorColumn = '- dark'
ColorColumn = '- dark'
NormalFloat = '- dark'
Visual = '- ui_blue'
VisualNOS = '- alt_bg'
WarningMsg = 'error_red bg'
DiffAdd = 'alt_bg sign_add'
DiffChange = 'alt_bg sign_change u'
DiffDelete = 'alt_bg sign_delete'
QuickFixLine = '- ui2_blue'
PmenuSbar = '- alt_bg'
PmenuThumb = '- gray'
MatchWord = '- - u'
MatchParen = 'hint_blue bg u'
MatchWordCur = '- - u'
MatchParenCur = '- - u'
Cursor = 'cursor_fg cursor_bg'
lCursor = 'cursor_fg cursor_bg'
CursorIM = 'cursor_fg cursor_bg'
TermCursor = 'cursor_fg cursor_bg'
TermCursorNC = 'cursor_fg cursor_bg'
Conceal = 'accent'
Directory = 'blue'
SpecialKey = 'blue - b'
Title = 'blue - b'
ErrorMsg = 'error_red bg b'
Search = 'light_gray search_blue'
IncSearch = 'search_orange light_gray'
Substitute = 'light_gray search_orange'
MoreMsg = 'orange'
Question = 'orange'
EndOfBuffer = 'bg'
NonText = 'bg'
Variable = 'light_blue'
String = 'orange'
Character = 'orange'
Constant = 'vivid_blue'
Number = 'light_green'
Boolean = 'blue'
Float = 'light_green'
Identifier = 'light_blue'
Function = 'yellow'
Operator = 'fg'
Type = 'cyan'
StorageClass = 'blue'
Structure = 'blue'
Typedef = 'blue'
Keyword = 'blue'
Statement = 'purple'
Conditional = 'blue'
Repeat = 'purple'
Label = 'purple'
Exception = 'purple'
Include = 'purple'
PreProc = 'purple'
Define = 'purple'
Macro = 'purple'
PreCondit = 'purple'
Special = 'orange'
SpecialChar = 'white'
Tag = 'blue'
Debug = 'red'
Delimiter = 'gray -'
SpecialComment = 'gray'
Underlined = '- - u'
Bold = '- - b'
Italic = '- - i'
Ignore = 'cyan bg b'
Todo = 'magenta bg b'
Error = 'error_red bg b'
TabLine = 'light_gray line'
TabLineSel = 'white line'
TabLineFill = 'line line'

[Treesitter]
TSComment = 'link:Comment'
TSAnnotation = 'blue'
TSAttribute = 'cyan'
TSConstructor = 'cyan'
TSType = 'cyan'
TSTypeBuiltin = 'orange'
TSConditional = 'yellow'
TSException = 'purple'
TSInclude = 'purple'
TSKeywordReturn = 'purple'
TSKeyword = 'purple'
TSKeywordFunction = 'purple'
TSLabel = 'light_blue'
TSNamespace = 'cyan'
TSRepeat = 'yellow'
TSConstant = 'orange'
TSConstBuiltin = 'orange'
TSFloat = 'orange'
TSNumber = 'orange'
TSBoolean = 'orange'
TSCharacter = 'green'
TSError = 'error_red'
TSFunction = 'blue'
TSFuncBuiltin = 'blue'
TSMethod = 'blue'
TSConstMacro = 'orange'
TSFuncMacro = 'blue'
TSVariable = 'light_blue'
TSVariableBuiltin = 'red'
TSProperty = 'red'
TSField = 'fg'
TSParameter = 'red'
TSParameterReference = 'red'
TSSymbol = 'light_blue'
TSText = 'alt_fg'
TSOperator = 'alt_fg'
TSPunctDelimiter = 'alt_fg -'
TSTagDelimiter = 'alt_fg'
TSTagAttribute = 'orange'
TSPunctBracket = 'alt_fg -'
TSPunctSpecial = 'purple'
TSString = 'green'
TSStringRegex = 'green'
TSStringEscape = 'green'
TSTag = 'blue'
TSEmphasis = '- - i'
TSUnderline = '- - u'
TSTitle = 'fg - -'
TSLiteral = 'orange'
TSURI = 'orange - u'
TSKeywordOperator = 'purple'
TSStructure = 'light_blue'
TSStrong = 'blue - b'
TSQueryLinterError = 'warning_orange'
TreesitterContext = '- tree_gray'

[markdown]
markdownBlockquote = 'green'
markdownCode = 'orange'
markdownCodeBlock = 'orange'
markdownCodeDelimiter = 'orange'
markdownH1 = 'blue'
markdownH2 = 'blue'
markdownH3 = 'blue'
markdownH4 = 'blue'
markdownH5 = 'blue'
markdownH6 = 'blue'
markdownHeadingDelimiter = 'blue'
markdownHeadingRule = 'fg - b'
markdownId = 'purple'
markdownIdDeclaration = 'blue'
markdownIdDelimiter = 'light_gray'
markdownLinkDelimiter = 'light_gray'
markdownBold = 'blue - b'
markdownItalic = '- - i'
markdownBoldItalic = 'yellow - bi'
markdownListMarker = 'blue'
markdownOrderedListMarker = 'blue'
markdownRule = 'accent'
markdownUrl = 'cyan - u'
markdownLinkText = 'blue'
markdownFootnote = 'orange'
markdownFootnoteDefinition = 'orange'
markdownEscape = 'yellow'

[Whichkey]
WhichKey = 'purple'
WhichKeySeparator = 'green'
WhichKeyGroup = 'blue'
WhichKeyDesc = 'light_blue'
WhichKeyFloat = '- dark'

[Git]
SignAdd = 'sign_add'
SignChange = 'sign_change'
SignDelete = 'sign_delete'
GitSignsAdd = 'sign_add'
GitSignsChange = 'sign_change'
GitSignsDelete = 'sign_delete'

[LSP]
LspDiagnosticsDefaultError = 'error_red'
LspDiagnosticsDefaultWarning = 'warning_orange'
LspDiagnosticsDefaultInformation = 'info_yellow'
LspDiagnosticsDefaultInfo = 'info_yellow'
LspDiagnosticsDefaultHint = 'hint_blue'
LspDiagnosticsVirtualTextError = 'error_red'
LspDiagnosticsVirtualTextWarning = 'warning_orange'
LspDiagnosticsVirtualTextInformation = 'info_yellow'
LspDiagnosticsVirtualTextInfo = 'info_yellow'
LspDiagnosticsVirtualTextHint = 'hint_blue'
LspDiagnosticsFloatingError = 'error_red'
LspDiagnosticsFloatingWarning = 'warning_orange'
LspDiagnosticsFloatingInformation = 'info_yellow'
LspDiagnosticsFloatingInfo = 'info_yellow'
LspDiagnosticsFloatingHint = 'hint_blue'
DiagnosticSignError = 'error_red'
DiagnosticSignWarning = 'warning_orange'
DiagnosticSignInformation = 'info_yellow'
DiagnosticSignInfo = 'info_yellow'
DiagnosticSignHint = 'hint_blue'
LspDiagnosticsSignError = 'error_red'
LspDiagnosticsSignWarning = 'warning_orange'
LspDiagnosticsSignInformation = 'info_yellow'
LspDiagnosticsSignInfo = 'info_yellow'
LspDiagnosticsSignHint = 'hint_blue'
LspDiagnosticsError = 'error_red'
LspDiagnosticsWarning = 'warning_orange'
LspDiagnosticsInformation = 'info_yellow'
LspDiagnosticsInfo = 'info_yellow'
LspDiagnosticsHint = 'hint_blue'
LspDiagnosticsUnderlineError = '- - u'
LspDiagnosticsUnderlineWarning = '- - u'
LspDiagnosticsUnderlineInformation = '- - u'
LspDiagnosticsUnderlineInfo = '- - u'
LspDiagnosticsUnderlineHint = '- - u'
LspReferenceRead = '- #2e303b'
LspReferenceText = '- #2e303b'
LspReferenceWrite = '- #2e303b'
LspCodeLens = 'context - i'
LspCodeLensSeparator = 'context - i'

[Telescope]
TelescopeSelection = 'hint_blue'
TelescopeMatching = 'info_yellow - b'
TelescopeBorder = 'blue bg'

[NvimTree]
NvimTreeFolderIcon = 'folder_blue'
NvimTreeIndentMarker = '#c5c5c5'
NvimTreeNormal = 'light_gray tree_gray'
NvimTreeVertSplit = 'alt_bg alt_bg'
NvimTreeFolderName = 'folder_blue'
NvimTreeOpenedFolderName = 'folder_blue - bi'
NvimTreeEmptyFolderName = 'gray - i'
NvimTreeGitIgnored = 'gray - i'
NvimTreeImageFile = 'light_gray'
NvimTreeSpecialFile = 'orange'
NvimTreeEndOfBuffer = 'tree_gray'
NvimTreeCursorLine = '- #282b37'
NvimTreeGitignoreIcon = '#E64A19'
NvimTreeGitStaged = 'tree_sign_add'
NvimTreeGitNew = 'tree_sign_add'
NvimTreeGitRenamed = 'tree_sign_add'
NvimTreeGitDeleted = 'sign_delete'
NvimTreeGitMerge = 'tree_sign_change'
NvimTreeGitDirty = 'tree_sign_change'

NvimTreeSymlink = 'cyan'
NvimTreeRootFolder = 'fg - b'
NvimTreeExecFile = '#9FBA89'

[Buffer]
BufferCurrent = 'fg bg'
BufferCurrentIndex = 'fg bg'
BufferCurrentMod = 'info_yellow bg'
BufferCurrentSign = 'hint_blue bg'
BufferCurrentTarget = 'red bg b'

BufferVisible = 'fg bg'
BufferVisibleIndex = 'fg bg'
BufferVisibleMod = 'info_yellow bg'
BufferVisibleSign = 'gray bg'
BufferVisibleTarget = 'red bg b'

BufferInactive = 'gray alt_bg'
BufferInactiveIndex = 'gray alt_bg'
BufferInactiveMod = 'info_yellow alt_bg'
BufferInactiveSign = 'gray alt_bg'
BufferInactiveTarget = 'red alt_bg b'

[StatusLine]
StatusLine = 'line gray'
StatusLineNC = 'line gray'
StatusLineSeparator = 'line'
StatusLineTerm = 'line'
StatusLineTermNC = 'line'

[IndentBlankline]
IndentBlanklineContextChar = 'context'
IndentBlanklineContextStart = '- - u'
IndentBlanklineChar = 'dark_gray'
IndentBlanklineSpaceChar = 'cyan_test'
IndentBlanklineSpaceCharBlankline = 'info_yellow'

[Dashboard]
DashboardHeader = 'blue'
DashboardCenter = 'purple'
DashboardFooter = 'cyan'

[Cmp]
CmpItemAbbrDeprecated = 'gray - s'
CmpItemAbbrMatch = 'ui3_blue'
CmpItemAbbrMatchFuzzy = 'ui3_blue'
CmpItemKindFunction = 'blue'
CmpItemKindMethod = 'blue'
CmpItemKindConstructor = 'cyan'
CmpItemKindClass = 'cyan'
CmpItemKindEnum = 'cyan'
CmpItemKindEvent = 'yellow'
CmpItemKindInterface = 'cyan'
CmpItemKindStruct = 'cyan'
CmpItemKindVariable = 'red'
CmpItemKindField = 'red'
CmpItemKindProperty = 'red'
CmpItemKindEnumMember = 'orange'
CmpItemKindConstant = 'orange'
CmpItemKindKeyword = 'purple'
CmpItemKindModule = 'cyan'
CmpItemKindValue = 'fg'
CmpItemKindUnit = 'fg'
CmpItemKindText = 'fg'
CmpItemKindSnippet = 'yellow'
CmpItemKindFile = 'fg'
CmpItemKindFolder = 'fg'
CmpItemKindColor = 'fg'
CmpItemKindReference = 'fg'
CmpItemKindOperator = 'fg'
CmpItemKindTypeParameter = 'red'
